#!/usr/bin/env bash
# installs Nginx web server
# configure root to echo hello world
# first webpage

sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
