#!/usr/bin/env bash
# installs Nginx web server
# configure root to echo hello world
# first webpage

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/AJIyanu permanent;/" /etc/nginx/sites-available/default
sudo service nginx restart
