#!/usr/bin/env bash
# installs Nginx web server
# configure root to echo hello world
# first webpage
# Configure your Nginx server so that /redirect_me is redirecting to another page

apt-get -y update
apt-get -y install nginx
echo "Hello World" > /var/www/html/index.nginx-debian.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/AJIyanu permanent;/" /etc/nginx/sites-available/default
service nginx start
