#!/usr/bin/env bash
# install and comfigure a load balnacer
# with haproxy and roundrobin config

sudo apt update -y
sudo apt upgrade -y
apt-get -y install haproxy=1.6.\*
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
echo -e "frontend myfrontend
\tbind 0.0.0.0:80
\tdefault_backend myservers

backend myservers
\tbalance roundrobin
\tserver 11102-web-01 44.192.72.216:80 check
\tserver 11102-web-02 44.192.52.223:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
