#!/usr/bin/env bash
# run nginx as user nginx
pkill apache2
sed -i 's/80 default/8080 default/' /etc/nginx/sites-enabled/default
chmod 755 /etc/nginx/nginx.conf
find / -name "*nginx*" | chown -R nginx
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
su nginx -c 'service nginx start'
